_crate allowDamage false;

_crate = _this select 0;
["AmmoboxInit",[_crate,false,{true}]] spawn BIS_fnc_arsenal;

//Lists of items to include
_availableHeadgear = [
"H_mas_uk_beret",
 "H_mas_uk_bereta",
 "H_mas_uk_beretn",
 "H_mas_uk_PilotHelmetHeli_B",
 "H_mas_uk_CrewHelmetHeli_B",
 "H_mas_uk_HelmetCrew_B", 
 "H_mas_uk_MilCap_mcamo", 
 "H_mas_uk_MilCap_mcamo_v",
 "H_mas_uk_MilCap_mcamo_d",
 "H_mas_uk_MilCap_mcamo_m",
 "H_mas_uk_Cap", 
 "H_mas_uk_Cap_headphones",
 "H_mas_uk_Cap_headphones_d",
 "H_mas_uk_Cap_headphones_v", 
 "H_mas_uk_Cap_headphones_g",
 "H_mas_uk_revcapheadset_b", 
 "H_mas_uk_patrolheadset_b",
 "H_mas_uk_Woolhat",
 "H_mas_uk_Woolhat_c", 
 "H_mas_uk_Woolhat_w",
 "H_mas_uk_woolhat_ht",
 "H_mas_uk_woolhat_ht_w",
 "H_mas_uk_Booniehat_mult",
 "H_mas_uk_Booniehat_mtp",
 "H_mas_uk_Booniehat_rgr",
 "H_mas_uk_Booniehat_des",
 "H_mas_uk_Booniehat_mul_h",
 "H_mas_uk_Booniehat_mul_hm",
 "H_mas_uk_Booniehat_mul_hv",
 "H_mas_uk_Booniehat_mul_hd",
 "H_mas_uk_headset_b", 
 "H_mas_uk_Bandana", 
 "H_mas_uk_Bandana_h", 
 "H_mas_uk_helmet_mich_sf",
 "H_mas_uk_helmet_mich_sf_g", 
 "H_mas_uk_helmet_mich_sf_m", 
 "H_mas_uk_helmet_mich_sf_w",
 "H_mas_uk_helmet_mich_sf_b", 
 "H_mas_uk_helmet_mich_sf_gog",
 "H_mas_uk_helmet_mich_sf_gog_g",
 "H_mas_uk_helmet_mich_sf_gog_m",
 "H_mas_uk_helmet_mich_sf_gog_w", 
 "H_mas_uk_helmet_mich_sf_gog_b", 
 "H_mas_uk_helmet_mich_sf_h",
 "H_mas_uk_helmet_mich_sf_h_g",
 "H_mas_uk_helmet_mich_sf_h_m", 
 "H_mas_uk_helmet_mich_sf_h_w", 
 "H_mas_uk_helmet_mich_sf_h_b",
 "H_mas_uk_helmet_ops_sf", 
 "H_mas_uk_helmet_ops_sf_b",
 "H_mas_uk_helmet_ops_sf_g",
 "H_mas_uk_helmet_ops_sf_d", 
 "H_mas_uk_helmet_ops_sf_w", 
 "H_mas_uk_helmet_ops_sf_gog",
 "H_mas_uk_helmet_ops_sf_gog_b",
 "H_mas_uk_helmet_ops_sf_gog_g",
 "H_mas_uk_helmet_ops_sf_gog_d",
 "H_mas_uk_helmet_ops_sf_gog_w",
 "H_mas_uk_helmet_ops_sf_h", 
 "H_mas_uk_helmet_ops_sf_h_b", 
 "H_mas_uk_helmet_ops_sf_h_g",
 "H_mas_uk_helmet_ops_sf_h_d", 
 "H_mas_uk_helmet_ops_sf_h_w",
 "H_mas_uk_helmet_pro", 
 "H_mas_uk_helmet_pro_b",
 "H_mas_uk_helmet_pro_gog",
 "H_mas_uk_helmet_pro_gog_b"

];

_availableGoggles = [
"G_mas_wpn_gog",
 "G_mas_wpn_gog_d",
 "G_mas_wpn_gog_m",
 "G_mas_wpn_gog_md",
 "G_mas_wpn_gog_g",
 "G_mas_wpn_gog_gd",
 "G_mas_wpn_mask",
 "G_mas_wpn_mask_b",
 "G_mas_wpn_wrap",
 "G_mas_wpn_wrap_f",
 "G_mas_wpn_wrap_t",
 "G_mas_wpn_wrap_b",
 "G_mas_wpn_wrap_c",
 "G_mas_wpn_wrap_g",
 "G_mas_wpn_wrap_gog",
 "G_mas_wpn_wrap_gog_f",
 "G_mas_wpn_wrap_gog_t",
 "G_mas_wpn_wrap_gog_b",
 "G_mas_wpn_wrap_gog_c",
 "G_mas_wpn_wrap_gog_g",
 "G_mas_wpn_wrap_mask",
 "G_mas_wpn_wrap_mask_t",
 "G_mas_wpn_wrap_mask_f",
 "G_mas_wpn_wrap_mask_b",
 "G_mas_wpn_wrap_mask_c",
 "G_mas_wpn_wrap_mask_g",
 "G_mas_wpn_bala",
 "G_mas_wpn_bala_b",
 "G_mas_wpn_bala_t",
 "G_mas_wpn_bala_gog",
 "G_mas_wpn_bala_gog_b",
 "G_mas_wpn_bala_gog_t",
 "G_mas_wpn_bala_mask",
 "G_mas_wpn_bala_mask_b",
 "G_mas_wpn_bala_mask_t",
 "G_mas_wpn_shemag",
 "G_mas_wpn_shemag_r",
 "G_mas_wpn_shemag_w",
 "G_mas_wpn_shemag_gog",
 "G_mas_wpn_shemag_mask"
];

_availableUniforms = [
"U_mas_uk_B_CombatUniform_mtp",
 "U_mas_uk_B_CombatUniform_mtp_tshirt",
 "U_mas_uk_B_CombatUniform_mtp_vest",
 "U_mas_uk_B_CombatUniform_mcam",
 "U_mas_uk_B_CombatUniform_mcam_tshirt",
 "U_mas_uk_B_CombatUniform_mcam_vest",
 "U_mas_uk_B_CombatUniform_mcam1_vest",
 "U_mas_uk_B_CombatUniform_mcam2_vest",
 "U_mas_uk_B_CombatUniform_mcam3_vest",
 "U_mas_uk_B_CombatUniform_mcam4_vest",
 "U_mas_uk_B_CombatUniform_veg",
 "U_mas_uk_B_CombatUniform_veg_tshirt",
 "U_mas_uk_B_CombatUniform_veg_vest",
 "U_mas_uk_B_CombatUniform_veg1_vest",
 "U_mas_uk_B_CombatUniform_veg2_vest",
 "U_mas_uk_B_CombatUniform_veg3_vest",
 "U_mas_uk_B_CombatUniform_des",
 "U_mas_uk_B_CombatUniform_des_tshirt",
 "U_mas_uk_B_CombatUniform_des_vest",
 "U_mas_uk_B_CombatUniform_des1_vest",
 "U_mas_uk_B_CombatUniform_des2_vest",
 "U_mas_uk_B_CombatUniform_des3_vest",
 "U_mas_uk_B_CombatUniform_sage",
 "U_mas_uk_B_CombatUniform_sage_tshirt",
 "U_mas_uk_B_CombatUniform_sage_vest",
 "U_mas_uk_B_CRW", "U_mas_uk_B_wint",
 "U_mas_uk_B_pilot", "U_mas_uk_B_Wetsuit",
 "U_mas_uk_B_GhillieSuit",
 "U_mas_uk_B_GhillieSuit_v",
 "U_mas_uk_B_GhillieSuit_d",
 "U_mas_uk_B_GhillieSuit_w",
 "U_mas_uk_B_IndUniform1_o",
 "U_mas_uk_B_IndUniform2_o",
 "U_mas_uk_B_IndUniform1_m",
 "U_mas_uk_B_IndUniform2_m",
 "U_mas_uk_B_IndUniform1_v",
 "U_mas_uk_B_IndUniform2_v",
 "U_mas_uk_B_IndUniformx1",
 "U_mas_uk_B_IndUniformx2",
 "U_mas_uk_B_IndUniform1_d",
 "U_mas_uk_B_IndUniform2_d"

];

_availableVests = [
"V_mas_uk_Rangemaster_belt",
 "V_mas_uk_BandollierB_rgr",
 "V_mas_uk_PlateCarrier1_rgr",
 "V_mas_uk_PlateCarrier2_rgr",
 "V_mas_uk_PlateCarrierGL_rgr",
 "V_mas_uk_ChestrigB_rgr",
 "V_mas_uk_Rangemaster_belt_d",
 "V_mas_uk_BandollierB_rgr_d",
 "V_mas_uk_PlateCarrier1_rgr_d",
 "V_mas_uk_PlateCarrier2_rgr_d",
 "V_mas_uk_PlateCarrierGL_rgr_d",
 "V_mas_uk_ChestrigB_rgr_d",
 "V_mas_uk_Rangemaster_belt_v",
 "V_mas_uk_BandollierB_rgr_v",
 "V_mas_uk_PlateCarrier1_rgr_v",
 "V_mas_uk_PlateCarrier2_rgr_v",
 "V_mas_uk_PlateCarrierGL_rgr_v",
 "V_mas_uk_ChestrigB_rgr_v",
 "V_mas_uk_PlateCarrier1_rgr_g",
 "V_mas_uk_ChestrigB_rgr_g",
 "V_mas_uk_PlateCarrier1_rgr_w",
 "V_mas_uk_ChestrigB_rgr_w",
 "V_mas_uk_Rangemaster_belt_a",
 "V_mas_uk_BandollierB_rgr_a",
 "V_mas_uk_PlateCarrier1_rgr_a",
 "V_mas_uk_PlateCarrier2_rgr_a",
 "V_mas_uk_PlateCarrierGL_rgr_a",
 "V_mas_uk_ChestrigB_rgr_a",
 "V_mas_uk_Rangemaster_belt_t",
 "V_mas_uk_BandollierB_rgr_t",
 "V_mas_uk_PlateCarrier1_rgr_t",
 "V_mas_uk_PlateCarrier2_rgr_t",
 "V_mas_uk_PlateCarrierGL_rgr_t",
 "V_mas_uk_ChestrigB_rgr_t",
 "V_mas_uk_TacVest_p",
 "V_mas_uk_TacVest_g"

];

_availableBackpacks = [
"B_AssaultPack_rgr",
"B_AssaultPack_mcamo",
"B_Kitbag_rgr",
"B_Kitbag_mcamo",
"B_TacticalPack_blk",
"B_TacticalPack_mcamo"
];


//Populate with predefined items and whatever is already in the crate
[_crate,((backpackCargo _crate) + _availableBackpacks)] call BIS_fnc_addVirtualBackpackCargo;
[_crate,((itemCargo _crate) + _availableHeadgear + _availableGoggles + _availableUniforms + _availableVests)] call BIS_fnc_addVirtualItemCargo;
[_crate,(magazineCargo _crate)] call BIS_fnc_addVirtualMagazineCargo;
[_crate,(weaponCargo _crate)] call BIS_fnc_addVirtualWeaponCargo;   
